version: '2'
services:
  # Reach Technologies propritary middleware
  gateway:
    image: us.gcr.io/reach-hrsa-development/gateway
    #image: gcr.io/reach-hrsa-development/gateway
    environment:
      - SLACK_TOKEN=xoxp-xxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - SLACK_TEAM_ID=TDXXXXXX
      - TWILIO_ACCOUNT_SID=ACXXXXXXXXXXXXXXXXXXXXXXXX
      - TWILIO_AUTH_TOKEN=XXXXXXXXXXXXXXXXXXXXXXXXXXX
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    ports:
     - 5000:5000
    volumes:
      - ./gateway-server/:/app/
    links:
      - unomi

  unomi:
    image: mikeghen/unomi:1.3
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9300
    ports:
      - 8181:8181
      - 9443:9443
    links:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    environment:
      # - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - xpack.security.enabled=false
      - cluster.name=contextElasticSearch
    ports: # Expose Elasticsearch ports
      - "9300:9300"
      - "9200:9200"
