apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.9.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: gateway
  name: gateway
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: gateway
    spec:
      containers:
      - env:
        - name: FLASK_APP
          value: app.py
        - name: FLASK_ENV
          value: development
        - name: SLACK_TEAM_ID
          value: TD1FSS3L2
        - name: SLACK_TOKEN
          value: {{ .Values.slack.token }}
        - name: TWILIO_ACCOUNT_SID
          value: {{ .Values.twilio.account_sid }}
        - name: TWILIO_AUTH_TOKEN
          value: {{ .Values.twilio.auth_token }}
        - name: TWILIO_MESSAGE_SERVICE_SID
          value: {{ .Values.twilio.message_service_sid }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: gateway
        ports:
        - containerPort: 5000
        resources: {}
      restartPolicy: Always
status: {}
